# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Data Focused Python
tagline:          'A Jekyll theme'
description:      'Teaching informatin systems students the tools they need to do data science'
url:              https://drk-data-science.github.io/data-focused-python/
baseurl:          /

author:
  name:           'Brian Kolowitz'

github:
  repo:           https://github.com/drk-data-science/data-focused-python

gems:
  - jekyll-redirect-from

theme: jekyll-theme-hacker